#此流程 docker构建镜像 ssh服务器 docker拉取运行， 前端打包部署
name: Build and Deploy

on:
  push:
    branches:
      - test

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose build
          docker-compose push
        working-directory: ./NodeSever/

  deploy-docker:
    needs: build-and-push-docker # Fixed job dependency
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull tongque00/nodeserver:latest
            docker stop nodeserver || true
            docker rm nodeserver || true
            docker run -d --name nodeserver -p 3002:3002 tongque00/nodeserver:latest

            docker pull tongque00/tadmin:latest
            docker stop tadmin || true
            docker rm tadmin || true
            docker run -d --name tadmin -p 3003:3003 tongque00/tadmin:latest

  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Production Environment Variables
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> $GITHUB_ENV
          # Add other production environment variables as needed

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/*"
          target: "/opt/1panel/apps/openresty/openresty/www/sites/qimengstar/index/"
          rm: true
